### ISSUE TITLE
Side bar Highlights

### ISSUE THREAD

**Issue by s-a-m** [P2Pvalue/p2pvalue-website-code#30]
Highlights has Latest Contents and Key Facts. I'm not a designer but I think the style of Latest Contents is neither appealing, nor it matches with the look&feel of the rest of the website. 

Also, I'd remove the title "Highlights", as there are two titles then (either Highlights and Latest Contents, or Highlights and Key Facts). 

Probably I'd also change the style of the Twitter widget to match better with the website, and with the final version of the Latest Contents/etc. I understand though that if it's an external plugin it might be more difficult.

**Comment by drozas** [comment]
> Highlights has Latest Contents and Key Facts. I'm not a designer but I think the style of Latest Contents is neither appealing, nor it matches with the look&feel of the rest of the website. 

@cataspanglish / James, I'll reassign this to you, since this could be included as a change related to the new design and theme.

> Also, I'd remove the title "Highlights", as there are two titles then (either Highlights and Latest Contents, or Highlights and Key Facts). 

Done!

> Probably I'd also change the style of the Twitter widget to match better with the website, and with the final version of the Latest Contents/etc. I understand though that if it's an external plugin it might be more difficult.

There are some limitations from the Twitter API with this, but it is possible to tweak it a bit via the theme as well.  @cataspanglish / James, I'll reassign this to you, since this could be included as a change related to the new design and theme.
